appDir: ~/.dotfiles
dfNames:
- ~/.config/alacritty/alacritty.yml
- ~/.config/flake8
- ~/.conkyrc
- ~/.dotconfig.yml
- ~/.emacs.d/Cask
- ~/.emacs.d/Makefile
- ~/.emacs.d/custom.el
- ~/.emacs.d/init.el
- ~/.eslintrc
- ~/.ghci
- ~/.gitconfig
- ~/.hgrc
- ~/.ipython/profile_default/ipython_config.py
- ~/.irbrc
- ~/.jshintrc
- ~/.lein/profiles.clj
- ~/.mpdconf
- ~/.ncmpcpp/bindings
- ~/.profile
- ~/.pylintrc
- ~/.sbclrc
- ~/.screenrc
- ~/.stack/config.yaml
- ~/.tmux.conf
- ~/.vimperatorrc
- ~/.vimrc
- ~/.xinitrc
- ~/.zshrc
