appDir: ~/.dotfiles
dfNames:
- ~/.FBReader/config.changes
- ~/.Xresources
- ~/.compiz/default.profile
- ~/.config/synapse/config.json
- ~/.config/systemd/user/emacs.service
- ~/.conkyrc
- ~/.dotconfig.yml
- ~/.emacs.d/Cask
- ~/.emacs.d/Makefile
- ~/.emacs.d/init.el
- ~/.eslintrc
- ~/.ghci
- ~/.gitconfig
- ~/.hgrc
- ~/.ipython/profile_default/ipython_config.py
- ~/.irbrc
- ~/.jshintrc
- ~/.lein/profiles.clj
- ~/.mpdconf
- ~/.profile
- ~/.pylintrc
- ~/.sbclrc
- ~/.screenrc
- ~/.stack/config.yaml
- ~/.tmux.conf
- ~/.valgrindrc
- ~/.vimperatorrc
- ~/.vimrc
- ~/.xinitrc
- ~/.xmonad/xmonad.hs
- ~/.zshrc
